<a href="https://colab.research.google.com/github/shareefat/Deep_learning_Projects/blob/main/House_price_prediciton_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
df = pd.read_csv('/content/kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [79]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [80]:
df.drop(['date'],axis=1,inplace=True)

In [81]:
df.drop(['zipcode'],axis=1,inplace=True)

In [82]:
df.drop('view',axis=1,inplace=True)

In [83]:
df.drop(['lat','long'],axis=1,inplace=True)

In [84]:
df.head()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,3,7,1180,0,1955,0,1340,5650
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,3,7,2170,400,1951,1991,1690,7639
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,3,6,770,0,1933,0,2720,8062
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,5,7,1050,910,1965,0,1360,5000
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,3,8,1680,0,1987,0,1800,7503

In [85]:
x=df.drop('price', axis=1)
y=df['price']

In [86]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [88]:
x_train.shape

(17290, 15)

#Build ANN model

In [89]:
from tensorflow import keras
import tensorflow as tf

In [90]:
model=keras.models.Sequential([
    keras.layers.Dense(100,activation='relu',input_shape=(15,)),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(1,activation='linear'),
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

#loss function

In [91]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['R2Score'])

In [92]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - R2Score: -2.1413 - loss: 436168884224.0000
Epoch 2/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - R2Score: -1.8035 - loss: 379824472064.0000
Epoch 3/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - R2Score: -0.7477 - loss: 234938269696.0000
Epoch 4/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.0971 - loss: 124090408960.0000
Epoch 5/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.3493 - loss: 90351058944.0000
Epoch 6/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.4249 - loss: 80522838016.0000
Epoch 7/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.4584 - loss: 75150688256.0000
Epoch 8/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.4961 - loss: 70662471680.0000
Epoch 9/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.5129 - loss: 64269545472.0000
Epoch 10/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.5379 - loss: 63088357376.0000
Epoch 11/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.5679 - loss: 57021210624.0000
Epoch 12/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - R2Score: 0.5992 - loss: 55307149312.0000
Epoch 13/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.6051 - loss: 53374898176.0000
Epoch 14/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.6391 - loss: 50844413952.0000
Epoch 15/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - R2Score: 0.6483 - loss: 50205294592.0000
Epoch 16/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.6650 - loss: 45459374080.0000
Epoch 17/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6577 - loss: 45529669632.0000
Epoch 18/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6633 - loss: 46786322432.0000
Epoch 19/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - R2Score: 0.6680 - loss: 47207391232.0000
Epoch 20/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6797 - loss: 48700411904.0000
Epoch 21/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6719 - loss: 42927370240.0000
Epoch 22/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.6768 - loss: 42001965056.0000
Epoch 23/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.6905 - loss: 41773477888.0000
Epoch 24/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - R2Score: 0.6866 - loss: 45988487168.0000
Epoch 25/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.6756 - loss: 43456987136.0000
Epoch 26/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6973 - loss: 42291482624.0000
Epoch 27/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6794 - loss: 43404156928.0000
Epoch 28/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6851 - loss: 44084154368.0000
Epoch 29/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6854 - loss: 44287807488.0000
Epoch 30/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.6879 - loss: 41880547328.0000
Epoch 31/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - R2Score: 0.6882 - loss: 43697360896.0000
Epoch 32/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6846 - loss: 39617789952.0000
Epoch 33/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6778 - loss: 41063960576.0000
Epoch 34/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.6980 - loss: 45198032896.0000
Epoch 35/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6925 - loss: 41604411392.0000
Epoch 36/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.6982 - loss: 40735768576.0000
Epoch 37/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7069 - loss: 39210074112.0000
Epoch 38/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - R2Score: 0.6994 - loss: 42557616128.0000
Epoch 39/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - R2Score: 0.7029 - loss: 44540047360.0000
Epoch 40/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.7037 - loss: 41810550784.0000
Epoch 41/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6992 - loss: 45188751360.0000
Epoch 42/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7077 - loss: 40343449600.0000
Epoch 43/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - R2Score: 0.6960 - loss: 40322531328.0000
Epoch 44/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - R2Score: 0.7031 - loss: 39051681792.0000
Epoch 45/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - R2Score: 0.7064 - loss: 38525726720.0000
Epoch 46/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.7056 - loss: 42732826624.0000
Epoch 47/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7088 - loss: 43043414016.0000
Epoch 48/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7169 - loss: 41451130880.0000
Epoch 49/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7105 - loss: 41801445376.0000
Epoch 50/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7104 - loss: 39784071168.0000
Epoch 51/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6895 - loss: 38463586304.0000
Epoch 52/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7101 - loss: 39254835200.0000
Epoch 53/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7176 - loss: 39048482816.0000
Epoch 54/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.6954 - loss: 41429331968.0000
Epoch 55/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7051 - loss: 41567100928.0000
Epoch 56/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - R2Score: 0.7156 - loss: 42914840576.0000
Epoch 57/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7056 - loss: 41395785728.0000
Epoch 58/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7057 - loss: 38847995904.0000
Epoch 59/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7146 - loss: 42383773696.0000
Epoch 60/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7136 - loss: 39408836608.0000
Epoch 61/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7149 - loss: 42643894272.0000
Epoch 62/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7114 - loss: 36867944448.0000
Epoch 63/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7199 - loss: 38567378944.0000
Epoch 64/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7112 - loss: 40466608128.0000
Epoch 65/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7175 - loss: 37850537984.0000
Epoch 66/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.7103 - loss: 41915195392.0000
Epoch 67/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7196 - loss: 41458130944.0000
Epoch 68/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7086 - loss: 39718969344.0000
Epoch 69/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7178 - loss: 39034843136.0000
Epoch 70/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7098 - loss: 37620387840.0000
Epoch 71/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7072 - loss: 39246364672.0000
Epoch 72/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7122 - loss: 36455874560.0000
Epoch 73/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7165 - loss: 38790217728.0000
Epoch 74/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7087 - loss: 37988597760.0000
Epoch 75/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7201 - loss: 39887945728.0000
Epoch 76/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - R2Score: 0.7085 - loss: 42869768192.0000
Epoch 77/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - R2Score: 0.7128 - loss: 39148371968.0000
Epoch 78/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7206 - loss: 38414258176.0000
Epoch 79/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7211 - loss: 40430903296.0000
Epoch 80/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7210 - loss: 40505245696.0000
Epoch 81/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7150 - loss: 39658635264.0000
Epoch 82/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7229 - loss: 38070272000.0000
Epoch 83/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7191 - loss: 37734633472.0000
Epoch 84/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7192 - loss: 39533256704.0000
Epoch 85/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7070 - loss: 38158917632.0000
Epoch 86/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - R2Score: 0.7265 - loss: 40055877632.0000
Epoch 87/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.7236 - loss: 41190084608.0000
Epoch 88/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7110 - loss: 39624855552.0000
Epoch 89/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7177 - loss: 39986585600.0000
Epoch 90/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7219 - loss: 35991457792.0000
Epoch 91/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7262 - loss: 37559939072.0000
Epoch 92/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7197 - loss: 37511135232.0000
Epoch 93/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7215 - loss: 36988977152.0000
Epoch 94/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7255 - loss: 37462257664.0000
Epoch 95/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7223 - loss: 36490338304.0000
Epoch 96/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7266 - loss: 39337242624.0000
Epoch 97/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - R2Score: 0.7319 - loss: 35922685952.0000
Epoch 98/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - R2Score: 0.7322 - loss: 36055097344.0000
Epoch 99/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - R2Score: 0.7263 - loss: 37289017344.0000
Epoch 100/100
541/541 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - R2Score: 0.7081 - loss: 37204271104.0000

In [93]:
model.evaluate(x_test,y_test)

136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - R2Score: 0.7133 - loss: 36027555840.0000

[34341578752.0, 0.7112310528755188]

In [97]:
from sklearn.metrics import r2_score
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)*100

136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

71.12315110442078

In [101]:
y_test[:5]

17384     297000.0
722      1578000.0
2680      562100.0
18754     631500.0
14554     780000.0
Name: price, dtype: float64

In [102]:
y_pred[:5]

array([[ 375157.47],
       [1681450.6 ],
       [ 498891.7 ],
       [ 589983.2 ],
       [ 695112.4 ]], dtype=float32)